# Generated by Django 4.2.2 on 2023-08-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rajapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
